#!/usr/bin/env ruby

#!/usr/bin/env ruby
# frozen_string_literal: true
require "bundler/setup"
require 'pry'
begin
    require "revpro/cli"
rescue LoadError
    require_relative '../lib/revpro/cli'
end

Dry::CLI.new(Revpro::CLI::Commands).call